name: Generate and Push File Tree

on:
  workflow_dispatch: # Manual trigger

jobs:
  generate_file_tree:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the file tree JSON
      - name: Generate File Tree
        id: generate_tree
        run: |
          echo "Generating file tree..."
          tree -J > file_tree.json
          echo "File tree generated."

      # Step 3: Configure Git for Push
      - name: Configure Git for Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 4: Set remote URL to push to `AndresMGA.github.io`
      - name: Set Remote Repository URL
        run: |
          git remote set-url origin https://github.com/AndresMGA/AndresMGA.github.io.git

      # Step 5: Add, commit, and push the JSON file to `AndresMGA.github.io`
      - name: Commit and Push File Tree to GitHub Pages Repository
        run: |
          git add file_tree.json
          git diff --quiet || git commit -m "Generate file tree JSON"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
