name: Generate and Push File Tree

on:
  workflow_dispatch: # Manual trigger

jobs:
  generate_file_tree:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the file tree JSON
      - name: Generate File Tree
        id: generate_tree
        run: |
          echo "Generating file tree..."
          tree -J > file_tree.json
          echo "File tree generated."

      # Step 3: Commit and push the JSON file back to the repository
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push File Tree
        run: |
          git add file_tree.json
          git commit -m "Generate file tree JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
