name: Update File Tree JSON

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger on pull requests to the main branch
  workflow_dispatch:  # Allow manual execution of the workflow

permissions:
  contents: write  # Ensure the token has write permissions to commit changes

jobs:
  update-file-tree:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Node.js (for JSON generation script)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use a stable Node.js version

      # Step 3: Generate hierarchical file tree JSON
      - name: Generate hierarchical file tree JSON
        run: |
          # Create a Node.js script to generate the file tree
          cat << 'EOF' > generateFileTree.js
          const fs = require('fs');
          const path = require('path');

          function generateTree(dir, isRoot = false) {
              const result = {};
              fs.readdirSync(dir).forEach(file => {
                  // Ignore hidden files and directories
                  if (file.startsWith('.')) return;

                  const fullPath = path.join(dir, file);
                  const stats = fs.statSync(fullPath);

                  // Ignore files at the root level
                  if (isRoot && stats.isFile()) return;

                  if (stats.isDirectory()) {
                      result[file] = generateTree(fullPath); // Recurse into subdirectories
                  } else {
                      result[file] = null; // For files, just add as objects with null value
                  }
              });
              return result;
          }

          // Generate the tree for the current directory (root)
          const tree = generateTree('.', true);

          // Write the generated tree to a JSON file
          fs.writeFileSync('file_tree.json', JSON.stringify(tree, null, 2));
          EOF

          # Run the script
          node generateFileTree.js

      # Step 4: Commit and push changes
      - name: Commit and push changes
        run: |
          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Stage and commit the file
          git add file_tree.json
          git commit -m "Update file_tree.json [skip ci]" || echo "No changes to commit"

          # Push the changes back to the branch
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
